name: 'Validate GitHub Deploy Action'
on:
  pull_request:
    paths:
      - 'deploy/**'
      - 'plan/**'
      - '.github/workflows/lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          action: [ deploy, plan ]
    steps:
      - uses: actions/checkout@v5

      - name: Validate ${{ matrix.action }}/action files
        id: validate
        run: |
          npm install -g ajv-cli ajv-formats js-yaml
          curl -fsSL -o action-schema.json https://www.schemastore.org/github-action.json
          echo "Validating against schema..."
          ajv validate \
              --all-errors \
              --verbose \
              -s action-schema.json \
              -d ./${{ matrix.action }}/action.yml || {
                echo "";
                echo "✗ Schema validation failed.";
                exit 1;
              }
          echo "✓ Validation passed!"