name: 'Validate GitHub Deploy Action'
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Validate deploy/action.yml file
        id: validate
        run: |
          npm install -g ajv-cli ajv-formats js-yaml
          curl -fsSL -o action-schema.json https://www.schemastore.org/github-action.json
          echo "Validating against schema..."
          ajv validate \
              --all-errors \
              --verbose \
              -s action-schema.json \
              -d ./deploy/action.yml || {
                echo "";
                echo "✗ Schema validation failed.";
                exit 1;
              }
          echo "✓ Validation passed!"