name: 'Test CLI Action'
on:
  workflow_dispatch:
    ## Future input to test against different environments
   #inputs:
    #environment:
      #description: 'Environment to test CLI against'
      #required: false
      #default: 'staging'
      #type: choice
      #options:
        #- staging
        #- production

# set staging flag to always hit sanity.work
# can leverage input above in future to test prod
env:
  SANITY_INTERNAL_ENV: 'staging'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running CLI Action:"

      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - run: echo "Installing dependencies..."
      - name: Install dependencies
        run: npm ci
        working-directory: ./tests

      - name: Deploy Blueprint to sanity.work
        uses: ./
        with:
          sanity-token: ${{ secrets.SANITY_TOKEN }}
          stack-id: ${{ secrets.STACK_ID }}
          project-id: ${{ secrets.PROJECT_ID }}
          organization-id: ${{ secrets.ORGANIZATION_ID }}
          working-directory: "./tests"

